version: '3.8'
services:
  postgresDB:
    image: postgres:latest
    environment:
      POSTGRES_DB: gymDB-dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      -  postgres_data_dev:/var/lib/postgresql/data/
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: postgres
#    volumes:
#        - ./servers.json:/pgadmin4/servers.json
    ports:
      - 80:80
    depends_on:
      - postgresDB

  app:
    image: myapp
    environment:
      DB_HOST: postgresDB
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      - postgresDB
      - redis
    ports:
      - 8080:8080

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./src/main/resources/prometheus.yaml:/etc/prometheus/prometheus.yaml
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    ports:
      - 9090:9090
    depends_on:
      - app

  redis:
    image: redis:latest
    command: [ "redis-server", "--protected-mode", "no"]
    ports:
      - 6379:6379

volumes:
  postgres_data_dev: