version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: gym
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
        - ./servers.json:/pgadmin4/servers.json
    ports:
      - 8080:80
    depends_on:
      - db

  app:
    image: myapp
    environment:
      DB_HOST: db
    depends_on:
      - db
volumes:
  postgres_data: