#LOGGING CONFIGURATION
logging:
  pattern:
    console: "%clr(%d{${LOG_DATEFORMAT:yyy-MM-dd'T'HH:mm:ss.SSSXXX}}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %X{correlationId:- } %X{txId:- } %msg%n"
  level:
    root: INFO

#SPRING CONFIGURATION
spring:
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: create
        format_sql: true
        use_sql_comments: true
        show_sql: true
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/gymDB-dev
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

#SPRING-DOC SWAGGER CONFIGURATION
springdoc:
  swagger-ui:
    url: /swagger-config.yml
    enabled: true

#ACTUATOR CONFIGURATION
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'


#JWT
token:
  signing:
    key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855