#LOGGING CONFIGURATION
logging:
  #pattern:
    #console: "%clr(%d{${LOG_DATEFORMAT:-yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx} [%X{transactionId:- }] - %msg%n"
  level:
    root: INFO


#SPRING CONFIGURATION
hibernate:
  show_sql: true
  hbm2ddl:
    auto: update
  format_sql: true
  use_sql_comments: true
db:
  driver: org.postgresql.Driver
  url: jdbc:postgresql://${DB_HOST:localhost}:5432/gym
  username: postgres
  password: postgres
