#LOGGING CONFIGURATION
logging:
  pattern:
    console: "%clr(%d{${LOG_DATEFORMAT:yyy-MM-dd'T'HH:mm:ss.SSSXXX}}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %X{correlationId:- } %X{txId:- } %msg%n"
  level:
    root: INFO

#SPRING CONFIGURATION
spring:
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/gym
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

#SPRING-DOC SWAGGER CONFIGURATION
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false