#LOGGING CONFIGURATION
logging:
  level:
    root: INFO

#SPRING CONFIGURATION
hibernate:
  show_sql: true
  hbm2ddl:
    auto: update
  format_sql: true
  use_sql_comments: true
db:
  driver: org.postgresql.Driver
  url: jdbc:postgresql://${DB_HOST:localhost}:5432/gym
  username: postgres
  password: postgres
