CREATE SEQUENCE trainee_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE trainer_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE training_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE training_type_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE usr_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE trainee (
                         date_of_birth DATE,
                         id BIGINT PRIMARY KEY,
                         usr_id BIGINT UNIQUE,
                         address VARCHAR(255)
);

CREATE TABLE trainee_trainer (
                                 trainee_id BIGINT NOT NULL,
                                 trainer_id BIGINT NOT NULL,
                                 PRIMARY KEY (trainee_id, trainer_id)
);

CREATE TABLE trainer (
                         id BIGINT PRIMARY KEY,
                         specialization_id BIGINT,
                         usr_id BIGINT UNIQUE
);

CREATE TABLE training (
                          training_date DATE NOT NULL,
                          training_duration INTEGER NOT NULL,
                          id BIGINT PRIMARY KEY,
                          trainee_id BIGINT,
                          trainer_id BIGINT,
                          training_type_id BIGINT,
                          training_name VARCHAR(255) NOT NULL
);

CREATE TABLE training_type (
                               id bigint GENERATED BY DEFAULT AS IDENTITY,
                               training_type_name varchar(255),
                               PRIMARY KEY (id)
);

CREATE TABLE usr (
                     is_active BOOLEAN NOT NULL,
                     id BIGINT PRIMARY KEY,
                     first_name VARCHAR(255) NOT NULL,
                     last_name VARCHAR(255) NOT NULL,
                     password VARCHAR(255) NOT NULL,
                     user_name VARCHAR(255) NOT NULL UNIQUE
);

ALTER TABLE trainee
    ADD FOREIGN KEY (usr_id)
        REFERENCES usr;

ALTER TABLE trainee_trainer
    ADD FOREIGN KEY (trainer_id)
        REFERENCES trainer;

ALTER TABLE trainee_trainer
    ADD FOREIGN KEY (trainee_id)
        REFERENCES trainee;

ALTER TABLE trainer
    ADD FOREIGN KEY (specialization_id)
        REFERENCES training_type;

ALTER TABLE trainer
    ADD FOREIGN KEY (usr_id)
        REFERENCES usr;

ALTER TABLE training
    ADD FOREIGN KEY (trainee_id)
        REFERENCES trainee;

ALTER TABLE training
    ADD FOREIGN KEY (trainer_id)
        REFERENCES trainer;

ALTER TABLE training
    ADD FOREIGN KEY (training_type_id)
        REFERENCES training_type;